name: lam3c
channels:
  - pytorch
  - nvidia/label/cuda-12.4.1
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - cuda
  - conda-forge::cudnn
  - gcc=13.2
  - gxx=13.2
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - pytorch-cuda=12.4
  - numpy<=1.26.4  # for random seed
  - ninja
  - scipy
  - addict
  - timm
  - psutil
  - huggingface_hub
  - open3d  # for demo visualization
  - matplotlib  # for demo visualization
  - pip:
    - --find-links https://data.pyg.org/whl/torch-2.5.0+cu124.html
    - torch-scatter
    - spconv-cu124
    - lark>=1.0.0
    - fire