name: dev-${PROJECT_NAME_ENV}
services:
  frontend:
    build:
      args:
        - BASE_IMAGE=node:23.9.0-bullseye-slim
        - PROJECT_NAME=${PROJECT_NAME_ENV}
        - SERVICE_NAME=frontend
        - USER_NAME=${USER_NAME_ENV}
        - GROUP_NAME=${GROUP_NAME_ENV}
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
      context: ../../
      dockerfile: environments/Dockerfile
    env_file:
      - ../envs.env
    tty: true
    init: true
    volumes:
        - ../../:/home/${USER_NAME_ENV}/${PROJECT_NAME_ENV}-frontend
    ports:
        - 3000:3000
        - 4173:4173
        - 5173:5173